Filatov hw1
siriusdevs/rpm-hws_7-1_2023 pull request #14
Opened 2023-03-30 14:57 UTC by rtrwslv

2023-04-02 11:01 UTC, siriusdevs commented
Your app has one button that returns 
> BrokenPipeError: [Errno 32] Broken pipe

this is humorous enough

2023-04-06 10:08 UTC, rtrwslv commented
Как удалось получить эту ошибку? Все функции работают без проблем
![image](https://user-images.githubusercontent.com/83144402/230346217-e08afb79-66fd-4b38-afbe-68541efa4d25.png)

2023-04-06 23:48 UTC, siriusdevs commented
and your page returns empty page after that
![image](https://user-images.githubusercontent.com/102812997/230513486-13ea25de-5d7f-45c3-bf0c-08936c244cc0.png)

2023-04-06 23:50 UTC, siriusdevs commented
this is not enough. our projects must contain a page working with db, this page must provide rest api requests processing with get/post/put/delete and a page with foreign api data. 
you have only one page and no docker/db on your project, which is sad at least :crying_cat_face:

2023-04-07 09:54 UTC, rtrwslv commented
Im using db for getting passwords and logins of users. If this is not enough - of course I can add some more pages)

2023-04-07 09:56 UTC, rtrwslv commented
> and your page returns empty page after that
> ![image](https://user-images.githubusercontent.com/102812997/230513486-13ea25de-5d7f-45c3-bf0c-08936c244cc0.png)

Still don't have any idea how u could achieve that error. What was the sequence of actions to get it?

2023-04-07 09:57 UTC, rtrwslv commented
> and a page with foreign api data.
Also have in project - jokes are getting from foreign api.

2023-04-07 10:01 UTC, rtrwslv commented
>Написать простой сайт на http.server по аналогии с нашим сайтом на семинарах. В нём должны быть данные из любой базы, минимум 3 страницы, любой сторонний API, должны работать запросы по REST с аутентификацией клиента.

In my opinion I've done everything from technical task - 3 pages (login page, main page, page with jokes), jokes are getting from foreign api, BUT I thought that writing my own authentication will be better, because It can be used for some more projects in future :) 

But im still not against to add something more in my project :)

2023-04-10 20:56 UTC, siriusdevs commented
what db do you use? ur project do not run any db or docker container.
also, i do not see any login pages. 
![image](https://user-images.githubusercontent.com/102812997/230997124-29112ecc-bf47-4b10-a91c-ff8754638468.png)
where is it? i only see 'humoreska' page. and i still get Broken pipe errrors. 

Your repo lacks a good readme!

2023-04-12 22:17 UTC, siriusdevs commented on README.md
> +docker run  -d \
you still did not fix this, i cant even run docker container for your project :(

2023-04-12 22:18 UTC, siriusdevs requested changes
pls fix your readme

2023-04-13 10:01 UTC, siriusdevs commented
creating table raises:
`ERROR:  schema "users" does not exist`

2023-04-13 10:02 UTC, siriusdevs commented
also, you do not create an extension

2023-04-13 10:07 UTC, siriusdevs commented
and provide examples of get/post/put/delete requests to send.

2023-04-13 11:18 UTC, rtrwslv commented
![image](https://user-images.githubusercontent.com/83144402/231742949-2faa33cf-5a65-4a17-a806-9286c095e083.png)
![image](https://user-images.githubusercontent.com/83144402/231742984-79a25576-8b60-4e09-a72d-6791dd10f02f.png)

2023-04-13 11:31 UTC, siriusdevs commented
1. linter
2. post/put requests
3. authorization

2023-04-14 07:52 UTC, rtrwslv commented
>authorization
What to do with that?

2023-04-14 08:01 UTC, rtrwslv commented
![image](https://user-images.githubusercontent.com/83144402/231982586-f5aceac9-9258-427e-8483-400de7d8640d.png)
![image](https://user-images.githubusercontent.com/83144402/231982636-3df32aab-a4a7-4278-ba72-a1d8b8a7bb06.png)

2023-04-23 13:46 UTC, siriusdevs commented
ERROR:  extension "humoreska" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/humoreska.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.


@rtrwslv  what is extension humoreska, exactly? oh boi, you should have attend lessons.. :smile:

2023-04-24 11:01 UTC, rtrwslv commented
Fixed ^^

2023-04-25 12:33 UTC, rtrwslv commented
Я регулярно захожу на гитхаб, и каждый раз смотрю, приняли ли домашку. Каждый раз она не принята. Я спрашивал уже раз 150 и 150 раз, но мой pull request не принят. Смысл в том, что отвечает мне один и тот же преподаватель, отвечает с неизменной интонацией. А я каждый раз с неизменной интонацией спрашиваю:
- домашку приняли?
- Пофиксить надо.

- закрыли pull request?
- Пока не все сделано по тз.

-  я все пофиксил и даже сделал линтер, теперь примете?
- Нет, надо было посещать пары.

- Я бы хотел узнать, сейчас все в порядке?
- Извините, пока что не могу принять.

- Первая домашка принята? Мне нужно бы закрыть ее уже.
- Мы их никогда не принимали.

И ведь этот преподаватель, знает меня идеально в лицо, знает, что я спрошу и знает, что он мне ответит. Но ещё ни разу ни один из нас ни жестом, ни словом не показал, что каждый из нас знает сценарий. Бывает преподаватель ведет у другой группы, когдя стою перед дверьми и подсматриваю за ним сквозь стеклянные двери, он равнодушно заканчивает пару, складывает вещи и спрашивает:
- Что вы хотели?
- Мне нужно сдать домашку.
- Пока что не могу принять.
- Жаль.

Иногда он общается с другим студентом, тогда, стоя рядом, я терпеливо жду, когда они закончат:
- А сегодня примете?
- Нет, у вас в линтере 32 ошибки в исключениях, а надо 31.

Иногда он просто скучает в деканате, когда пар нет, и только я жду его.  Конечно, он знает, что будет дальше, но не подаёт виду и равнодушно открывает гит.
- Что-то я не вижу себя в таблице, я там когда-нибудь буду?
- Нет, пока что не будешь, неправильный ридми.

Это очень суровое, по-настоящему мужское противостояние, исход которого не ясен. Очевидно, что каждая сторона рассчитывает на победу. Впрочем, я уже согласен на ничью.

2023-04-26 07:26 UTC, siriusdevs commented
1) ещё ни разу я не отклонил PR без причины. у вас всегда что-то не работает или ошибки в инструкции установки
2) не было такого, что PR отклонен, потому что "надо было ходить на пары". я говорю это, когда у вас ошибки, которых вы бы не допустили, если бы ходили на пары.

2023-04-26 07:29 UTC, siriusdevs commented
отправляю вам POST запрос
в вашем README, конечно же, ничего не указано - как, куда и что отправлять
отправляю POST на http://127.0.0.1:8001, json {"username": "new_name"}
ответ: could not get response, error: socket hang up
в терминале: /http_handler.py", line 54, in do_POST
    passsword = entered[1]
                ~~~~~~~^^^
IndexError: list index out of range

да, злой преподаватель опять не принимает рабочую домашку.

2023-04-26 11:05 UTC, rtrwslv commented
>1. ещё ни разу я не отклонил PR без причины. у вас всегда что-то не работает или ошибки в инструкции установки
не было такого, что PR отклонен, потому что "надо было ходить на пары". я говорю это, когда у вас ошибки, которых вы бы не допустили, если бы ходили на пары.

Это пересказ старого анекдота - примеры подбирались настолько же абсурдные, как и в оригинале - комичности ради :)

2023-04-28 12:55 UTC, siriusdevs commented
ничего не изменилась, падает с той же ошибкой на тот же запрос.

2023-04-28 15:30 UTC, rtrwslv commented
> ничего не изменилась, падает с той же ошибкой на тот же запрос.
Работает через put запрос в соответствии с ридми

2023-05-01 19:55 UTC, siriusdevs requested changes

2023-05-01 19:55 UTC, siriusdevs commented on setup.cfg
> +  WPS214
33 > 30

2023-05-01 19:55 UTC, siriusdevs commented on setup.cfg
> +# FIXME: this is a lot!
seems like.. fixed?

2023-05-02 19:20 UTC, siriusdevs commented
did you even try to run it?

humoreski.py", line 2, in <module>
    from config import API_URL
ImportError: cannot import name 'API_URL' from 'config'

2023-05-02 20:03 UTC, rtrwslv commented
> did you even try to run it?
> 
> humoreski.py", line 2, in from config import API_URL ImportError: cannot import name 'API_URL' from 'config'

Suddenly deleted while was cleaning code for linter

2023-05-04 14:11 UTC, merged