Add hm1
siriusdevs/rpm-hws_7-1_2023 pull request #3
Opened 2023-03-15 09:20 UTC by nazaroviktor2

2023-03-16 22:47 UTC, siriusdevs requested changes
could you please provide readme file?
users definetely need some instructions to start your project, dont you think?
see max228 readme for bad example.


I also see you empty tests :eyes:
django has nice testing submodules right there for you, use them.

2023-03-17 04:21 UTC, nazaroviktor2 commented
I don't have read.me in the root directory because that's where all my projects are.  The root directory is not a project.  But there is a read.me in each of the project folders to help the user get the project up and running.  If the user needs help with supported requests, then he must launch the application and go to the main page, where he will see the documentation for working with the application.

2023-03-17 08:12 UTC, nazaroviktor2 commented
> I also see you empty tests eyes django has nice testing submodules right there for you, use them.

Yes django has nice testing submodules. But my django app ***works with image api***. If this server is not running, django will return errors. And git workflows does not start the server with the image api. So I'll create tests for the app, ***I'll get a red X*** on git because the tests will fail

2023-03-19 21:27 UTC, siriusdevs requested changes
+ not enough tests.

you said that it is impossibru to run them, but i am not buying it. you chose this way yourself, stick with it
i believe in you :crossed_fingers: :four_leaf_clover:

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/django_nasa/urls.py
> +"""
excuse-moi, what is this in the name of God and Holy Django the Great?

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/django_nasa/wsgi.py
> +"""
again?

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/nasa/admin.py
> +"""Admin panel function."""
is there no admin panel in your project?
do you need an empty admin.py file though? is it compulsory to have it? (idk didnt try)

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/nasa/models.py
> +"""Models of nasa api."""
empty again

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/nasa/tests.py
> +"""Some tests for nasa."""
empty again

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/nasa/views.py
> +# Create your views here.
well, i do not think i will :smile:

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/templates/mars.html
> +      if (xhr.status === 200) {
that is some sirius js shit right there

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/templates/mars.html
> +
well, i am okay with that, by i suggest you show it to Иван Вячеславович.

2023-03-19 21:27 UTC, siriusdevs commented on django_nasa/templates/mars.html
> +
i am more than sure that there are MAP funcitons in js. and a lot more to make this code shrink to a tiny little script

2023-03-19 21:27 UTC, siriusdevs commented on image_api/http_config.py
> +"""Some http constants for image api."""
is there no way you return bad request code?

2023-03-19 21:27 UTC, siriusdevs commented on image_api/init.sql
> +create  extension if not exists  "uuid-ossp";
you do not need uuid extension just to mention uuid type. you need it to generate uuid value

2023-03-19 21:27 UTC, siriusdevs commented on image_api/tests/test_user_image.py
> +    assert II == 1
explain

2023-03-25 10:58 UTC, merged